#!/bin/bash
log "MacOS-specific dependency check"
log "run test to see if homebrew is installed"
type brew >/dev/null 2>&1 || {
  log "Brew is missing, attempting to install ..."
  # Homebrew recommends this folder for Macs with Intel chips:
  (cd /usr/local && \
    mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
  )
}
pass "homebrew is installed"
log "dependencies"
for dependency in curl tmux git openssl nvim source-highlight; do
  log "ensure dependency '$dependency' exists on the system"
  type $dependency >/dev/null 2>&1 || {
    log "Attempting to install $dependency using brew"
    com "brew install $dependency"
  }
done

