#!/bin/bash
log "MacOS-specific dependency check"
log "run test to see if homebrew is installed"
type brew >/dev/null 2>&1 || {
  fail "Brew is missing, please install homebrew"
  exit 1
}
pass "homebrew is installed"
log "dependencies"
for dependency in curl tmux git openssl nvim; do
  log "ensure dependency '$dependency' exists on the system"
  type $dependency >/dev/null 2>&1 || {
    log "Attempting to install $dependency using brew"
    com "brew install $dependency"
  }
done

