#!/bin/bash

log "checking dependencies"
for dependency in curl tmux git openssl; do
  log "ensure dependency '$dependency' exists on the system"
  type $dependency >/dev/null 2>&1 || {
    log "Attempting to install $dependency using apt"
    com "apt-get install $dependency -y"
  }
done

type nvim >/dev/null 2>&1 || {
  log "installing nvim"
  sudo add-apt-repository ppa:neovim-ppa/unstable
  sudo apt-get update
  sudo apt-get install neovim -y
  sudo apt install ruby ruby-dev python3-pip build-essential cmake libclang-dev libboost-all-dev -y && pip3 install --user --upgrade neovim
  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  
  log "get vim settings"
  git clone --depth=1 git@github.com:andrewsalveson/settings-vim
  cd settings-vim
  mkdir -p ~/.config/nvim
  mv * ~/.config/nvim
  cd ..
  rm -rf settings-vim
}
