#!/bin/bash

# text colors
RED="\033[91m"
GRN="\033[92m"
NRM="\033[0m"

TMP=./tmp
mkdir -p $TMP
LOG=$TMP/log.sh
if [ -f $LOG ]; then
  rm $LOG
fi
echo "#!/bin/bash" >> $LOG
VERBOSE=false

while getopts ":v" opt; do
  case ${opt} in
    v ) VERBOSE=true
      ;;
    \? ) echo "Usage: ./dboot [-v]"
      ;;
  esac
done

function log {
  LINE="#$1"
  if [ "$VERBOSE" = true ]; then
    echo -e $LINE
  fi
  echo -e $LINE >> $LOG
}

function pass {
  log "${GRN}$1${NRM}"
}

function fail {
  log "${RED}$1${NRM}"
}

function com {
  log "executing command"
  echo "$1" >> $LOG
  echo "$1"
  $1
}

log "run test to see if homebrew is installed"
type brew >/dev/null 2>&1 || {
  fail "Brew is missing, please install homebrew"
  exit 1
}

pass "homebrew is installed"

log "dependencies"
for dependency in curl tmux git; do
  log "ensure dependency '$dependency' exists on the system"
  type $dependency >/dev/null 2>&1 || {
    log "Attempting to install $dependency using brew"
    com "brew install $dependency"
  }
done
pass "dboot complete"

