#!/bin/bash
VERSION="0.3"

tput init

# temporarily move into dboot folder
OLDWD=$(pwd)
cd ~/dboot
. ./console

LOGO=./BLOKHEAD
BUILD=./WIDJIT
BG=./BG
BUILD_WIDTH=14

# print background
BG_LINES=$(cat $BG | wc -l | xargs)
tput dim
tput setaf 4
while IFS= read -r LINE
do
  echo "$LINE"
done <"$BG"
tput sgr0

# print logo
tput bold
tput setaf 6
LOGO_LINES=$(cat $LOGO | wc -l | xargs)
ROW=1
LONGEST=0
while IFS= read -r LINE
do
  LINE_CHARS=$(grep -o . <<<"$LINE" | wc -l)
  if [ $LINE_CHARS -gt $LONGEST ]; then
    LONGEST=$LINE_CHARS
  fi
  for COL in $(eval echo {0..$LINE_CHARS})
  do
    tput cup $ROW $COL
    CHAR="${LINE:$COL:1}"
    if [ "$CHAR" != "~" ]; then
      echo "${LINE:$COL:1}"
    fi
  done
  ROW=$((ROW+1))
done <"$LOGO"

COUNT=1
INSERT=$((LONGEST+4))
while IFS= read -r LINE
do
	tput cup $COUNT $INSERT
	echo "$LINE"
	COUNT=$((COUNT+1))
done <"$BUILD"


TOLAST=`expr \( $LOGO_LINES + 2 \)`
echo -e "$(tput cup 9 18)v${RED}$VERSION${NRM}$(tput cup 4 4)"

tput sgr0
tput cup $TOLAST



TMP=~/dboot/tmp
mkdir -p $TMP
LOG=$TMP/log.sh

# build temp and log (replay) script
if [ -f $LOG ]; then
  rm $LOG
fi
echo "#!/bin/bash" >> $LOG
chmod +x $LOG

info "OS: $OSTYPE"
set +a
if [[ "$OSTYPE" == "linux-gnu" ]]; then
  source ./dboot-unix-derivative
  source ./dboot-linux-gnu
elif [[ "$OSTYPE" == "linux-gnueabihf" ]]; then
  info "probably a Raspberry Pi"
  source ./dboot-unix-derivative
  source ./dboot-linux-gnueabihf
elif [[ "$OSTYPE" == "darwin"* ]]; then
  source ./dboot-unix-derivative
  source ./dboot-macos
elif [[ "$OSTYPE" == "msys" ]]; then
  source ./dboot-msys
elif [[ "$OSTYPE" == "cygwin" ]]; then
  fail "no scripts for cygwin"
elif [[ "$OSTYPE" == "freebsd"* ]]; then
  fail "no scripts for freebsd"
else
  fail "unknown OS"
fi

log "check repo status"
./git-check

source ./install
set -a

pass "dboot complete"

# return to original working directory
cd $OLDWD

