#!/bin/bash
log "get Linux flavor"
if [ -f /etc/os-release ]; then
	# feedesktop.org and systemd
	. /etc/os-release
	OS=$NAME
	VER=$VERSION_ID
elif type lsb_release >/dev/null 2>&1; then
	# linuxbase.org
	OS=$(lsb_release -si)
	VER=$(lsb_release -sr)
elif [ -f /etc/lsb-release ]; then
	# for some versions of Debian/Ubuntu without lsb_release command
	. /etc/lsb-release
	OS=$DISTRIB_ID
	VER=$DISTRIB_RELEASE
elif [ -f /etc/SuSe-release ]; then
	# older SuSE/etc.
	fail "SuSe not supported"
elif [ -f /etc/redhat-release ]; then
	# Older Red Hat, CentOS, etc.
	fail "Red Hat not supported"
else
	#fallback to uname
	OS=$(uname -s)
	VER=$(uname -r)
fi

info "linux flavor: $OS"
info "release: $VER"

case $OS in
	Ubuntu ) source ./dboot-ubuntu
		;;
	\? ) fail "no script for $OS"
		;;
esac

