#!/bin/bash

log "checking dependencies"
for dependency in curl tmux git openssl; do
  log "ensure dependency '$dependency' exists on the system"
  type $dependency >/dev/null 2>&1 || {
    log "Attempting to install $dependency using apt"
    com "apt-get install $dependency -y"
  }
done

type powerline >/dev/null 2>&1 || {
  # requires sudo for some reason ...
  sudo apt install --yes powerline
}

type nvim >/dev/null 2>&1 || {
  log "installing nvim"
  if [ "$EUID" -ne 0 ]; then
    sudo add-apt-repository ppa:neovim-ppa/unstable
    sudo apt-get update
    sudo apt-get install neovim -y
    sudo apt install ruby ruby-dev python3-pip build-essential cmake libclang-dev libboost-all-dev -y && pip3 install --user --upgrade neovim
  else
    add-apt-repository ppa:neovim-ppa/unstable
    apt-get update
    apt-get install neovim -y
    apt install ruby ruby-dev python3-pip build-essential cmake libclang-dev libboost-all-dev -y && pip3 install --user --upgrade neovim
  fi
  curl -fLo ~/.config/nvim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  
  log "get vim settings"
  git clone --depth=1 git@github.com:andrewsalveson/settings-vim
  cd settings-vim
  mkdir -p ~/.config/nvim
  mv * ~/.config/nvim
  cd ..
  rm -rf settings-vim
}
