#!/bin/bash
. ./console
EXPIRY=3600

if [[ -f last_git_check ]]; then
  LAST=$(cat last_git_check)
  SINCE=`expr $(date +%s) - $LAST`
  if [ "$SINCE" -lt "$EXPIRY" ]; then
    pass "this fruit is fresh"
    exit 0
  fi
fi

date +%s > last_git_check

log "check for new version"

./repo-check

if ( git ls-remote ) then
  DBHASH=$(openssl dgst -sha256 ./dboot)
  git pull origin master
  NEWDBHASH=$(openssl dgst -sha256 ./dboot)
  if [ "$DBHASH" = "$NEWDBHASH" ]; then
    pass "no updates"
    exit 0
  else
    ./dboot
  fi
else
  fail "could not find git remote"
fi

