#!/bin/bash

cd rc
log "check installation in shell startup scripts"
for RCF in .bashrc .zshrc;do
  log "performing installation check for $RCF"
  if [ -f ~/$RCF ]; then
    if fgrep -q '#BEGIN dboot' ~/$RCF
    then
      pass "dboot already added to $RCF"
    else
      log "appending dboot to $RCF"
      cat ./$RCF >> ~/$RCF
    fi
  else
    fail "could not find $RCF"
  fi
done
cd ..
pass "rc files installed"

